language: node_js
version: 1.0
node_js:
- 13
before_script:
- export TZ=Europe/Brussels
script:
  - npm run lint
  - npm run test
  - npm run bundle
deploy:
  - provider: npm
    edge: true
    email: matti@seats.io
    api_key:
        secure: $NPM_API_KEY
    on:
        tags: true
  - provider: releases
    edge: true
    api_key:
        secure: $GITHUB_OAUTH
    file: build/SeatsioClient.js
    on:
        tags: true
