name: 'Version bump'

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'minor or major'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      with:
        node-version: 13
        registry-url: https://registry.npmjs.org/
      - run: npm version ${{ inputs.versionType }}
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
